export const USER_ROLES_GET_ALL_REQUEST = 'USER_ROLES_GET_ALL_REQUEST';
export const USER_ROLES_GET_ALL_SUCCESS = 'USER_ROLES_GET_ALL_SUCCESS';
export const USER_ROLES_GET_ALL_FAILURE = 'USER_ROLES_GET_ALL_FAILURE';

export const USER_ROLE_DETAIL_GET_REQUEST = 'USER_ROLE_DETAIL_GET_REQUEST';
export const USER_ROLE_DETAIL_GET_SUCCESS = 'USER_ROLE_DETAIL_GET_SUCCESS';
export const USER_ROLE_DETAIL_GET_FAILURE = 'USER_ROLE_DETAIL_GET_FAILURE';