export const USERS_GET_ALL_REQUEST = 'USERS_GET_ALL_REQUEST';
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS';
export const USERS_GET_ALL_FAILURE = 'USERS_GET_ALL_FAILURE';

export const USER_DETAIL_GET_REQUEST = 'USER_DETAIL_GET_REQUEST';
export const USER_DETAIL_GET_SUCCESS = 'USER_DETAIL_GET_SUCCESS';
export const USER_DETAIL_GET_FAILURE = 'USER_DETAIL_GET_FAILURE';

export const CUSTOMERS_GET_ALL_REQUEST = 'CUSTOMERS_GET_ALL_REQUEST';
export const CUSTOMERS_GET_ALL_SUCCESS = 'CUSTOMERS_GET_ALL_SUCCESS';
export const CUSTOMERS_GET_ALL_FAILURE = 'CUSTOMERS_GET_ALL_FAILURE';

export const CUSTOMER_DETAIL_GET_REQUEST = 'CUSTOMER_DETAIL_GET_REQUEST';
export const CUSTOMER_DETAIL_GET_SUCCESS = 'CUSTOMER_DETAIL_GET_SUCCESS';
export const CUSTOMER_DETAIL_GET_FAILURE = 'CUSTOMER_DETAIL_GET_FAILURE';

export const USER_ROLES_GET_ALL_REQUEST = 'USER_ROLES_GET_ALL_REQUEST';
export const USER_ROLES_GET_ALL_SUCCESS = 'USER_ROLES_GET_ALL_SUCCESS';
export const USER_ROLES_GET_ALL_FAILURE = 'USER_ROLES_GET_ALL_FAILURE';

export const USER_ROLE_DETAIL_GET_REQUEST = 'USER_ROLE_DETAIL_GET_REQUEST';
export const USER_ROLE_DETAIL_GET_SUCCESS = 'USER_ROLE_DETAIL_GET_SUCCESS';
export const USER_ROLE_DETAIL_GET_FAILURE = 'USER_ROLE_DETAIL_GET_FAILURE';

export const CREATE_USER_ROLES_REQUEST = 'CREATE_USER_ROLES_REQUEST';
export const CREATE_USER_ROLES_SUCCESS = 'CREATE_USER_ROLES_SUCCESS';
export const CREATE_USER_ROLES_FAILURE = 'CREATE_USER_ROLES_FAILURE';

export const EDIT_USER_ROLES_REQUEST = 'EDIT_USER_ROLES_REQUEST';
export const EDIT_USER_ROLES_SUCCESS = 'EDIT_USER_ROLES_SUCCESS';
export const EDIT_USER_ROLES_FAILURE = 'EDIT_USER_ROLES_FAILURE';

export const PERMISSION_GET_ALL_REQUEST = 'PERMISSION_GET_ALL_REQUEST';
export const PERMISSION_GET_ALL_SUCCESS = 'PERMISSION_GET_ALL_SUCCESS';
export const PERMISSION_GET_ALL_FAILURE = 'PERMISSION_GET_ALL_FAILURE';